"""
Full end-to-end coverage smoke test — port of the Streamlit-era
``scripts/full_coverage_test.py`` to the FastAPI codebase.

Creates a fresh test client + project, builds a complete Meeting (attendees,
agenda items, discussion points with sub-points, action items, deliverables,
closing remarks), then generates the meeting-minutes PDF. Uses that Meeting
as the source for a pre-meeting coordination agenda with every section
populated — including the Schedule Change Log — and generates the agenda PDF.

Outputs land in ``backend/data/outputs/`` with the ``TEST_`` prefix.

The DB rows created here are LEFT IN PLACE so the test client/project shows
up in the React UI's ContextSwitcher afterward — delete via the UI (or this
script's purge-then-recreate behaviour) if you don't want them.

Run from the backend dir:
    cd backend
    python -m scripts.full_coverage_test
"""
from __future__ import annotations

import sys
from datetime import date, timedelta
from pathlib import Path

# Make `backend/` importable when run as `python scripts/full_coverage_test.py`
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from db.session import get_session_factory, init_db
from db.models import (
    Client, Project, Meeting, MeetingAttendee, AgendaItem,
    DiscussionPoint, ActionItem, Deliverable, MeetingDeliverable,
    Schedule, Agenda,
)
from db.repository import save_agenda, open_actions, deliverables_to_carry_forward
from core.services import safe_filename_slug, build_draft_meeting_view
from docgen import (
    generate_meeting_minutes_pdf,
    generate_premeeting_agenda_pdf,
)
from llm.providers import ParsedDiscussionPoint as P


def _dps_to_text(dps, level: int = 0) -> str:
    """Serialize a ParsedDiscussionPoint tree into the indented-bullet text
    format the textareas use ("- Label: content", 2-space indent per level)."""
    if not dps:
        return ""
    out = []
    indent = "  " * level
    for dp in dps:
        label = (dp.label or "").strip()
        content = (dp.content or "").strip()
        body = f"{label}: {content}" if label else content
        out.append(f"{indent}- {body}")
        kids = getattr(dp, "sub_points", None) or []
        if kids:
            child = _dps_to_text(kids, level + 1)
            if child:
                out.append(child)
    return "\n".join(filter(None, out))


TEST_CLIENT_NAME = "TestCo Renewables"
TEST_PROJECT_NAME = "Full Coverage Sample"

OUTPUT_DIR = Path("data/outputs")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)


def _purge_prior_test_data(session) -> None:
    """Remove any pre-existing test client + project so the run is fresh."""
    existing_project = (
        session.query(Project).filter_by(name=TEST_PROJECT_NAME).first()
    )
    if existing_project:
        session.delete(existing_project)
    existing_client = (
        session.query(Client).filter_by(name=TEST_CLIENT_NAME).first()
    )
    if existing_client:
        session.delete(existing_client)
    session.flush()


def _build_test_meeting(session) -> tuple[Client, Project, Meeting]:
    """Build client → project → schedule → meeting with full content."""
    client = Client(
        name=TEST_CLIENT_NAME,
        email_domain="testco-renewables.com",
    )
    session.add(client)
    session.flush()

    project = Project(
        client_id=client.id,
        name=TEST_PROJECT_NAME,
        scope="Electrical Design, Civil Design, Structural Studies",
        schedule_version="V3",
    )
    session.add(project)
    session.flush()

    schedule = Schedule(
        project_id=project.id,
        version="V3",
        source_filename="Test_Schedule_V3.pdf",
        source_format="pdf",
        project_start_date=date.today() - timedelta(days=60),
        total_duration_days=180,
        total_price=420_000,
    )
    session.add(schedule)

    meeting_date = date.today() - timedelta(days=3)
    meeting = Meeting(
        project_id=project.id,
        meeting_date=meeting_date,
        title=f"Weekly coordination — {meeting_date.isoformat()}",
        raw_notes="(generated by full_coverage_test.py)",
        closing_remarks=(
            "Strong forward progress across electrical, civil, and structural. "
            "Next session will focus on locking the transformer source decision "
            "and verifying the AHJ permit cycle. Thank you all for the time."
        ),
        stage="final",
        schedule_version_at_meeting="V3",
    )
    session.add(meeting)
    session.flush()

    attendees = [
        ("Arun Ramadass",       "AR", "Castillo Engineering"),
        ("Rick Castillo",       "RC", "Castillo Engineering"),
        ("Roashaael Mary John", "RM", "Castillo Engineering"),
        ("Cheyne Matheny",      "CM", "Castillo Engineering"),
        ("Mark Jordan",         "MJ", "TestCo Renewables"),
        ("Elizabeth Wuest",     "EW", "TestCo Renewables"),
        ("Andrew Proctor",      "AP", "Sunshare Construction"),
        ("Jalen Wheeler",       "JW", "Sunshare Construction"),
        ("Dylan Wraga",         "DW", "Ampacity Engineering"),
        ("Hossein Karami",      "HK", "Geotech Partners"),
    ]
    for full_name, init, org in attendees:
        session.add(MeetingAttendee(
            meeting_id=meeting.id,
            full_name=full_name, initials=init, organization=org,
        ))

    agenda_items = [
        ("Review of last week's actions",      "General"),
        ("Civil — drainage and grading",       "Civil"),
        ("Electrical — recloser & ampacity",   "Electrical"),
        ("Structural — module-rack tilt change","Structural"),
        ("Permitting status and next steps",   "General"),
        ("Open discussion + action assignments","General"),
    ]
    for idx, (text, disc) in enumerate(agenda_items):
        session.add(AgendaItem(
            meeting_id=meeting.id, order_index=idx,
            text=text, discipline=disc,
        ))

    def _add_dp(parent_id, idx, label, content, disc, subs=()):
        dp = DiscussionPoint(
            meeting_id=meeting.id, parent_id=parent_id,
            order_index=idx, label=label, content=content,
            discipline=disc, ai_extracted=False,
        )
        session.add(dp)
        session.flush()
        for s_idx, (s_label, s_content) in enumerate(subs):
            session.add(DiscussionPoint(
                meeting_id=meeting.id, parent_id=dp.id,
                order_index=s_idx, label=s_label, content=s_content,
                discipline=disc, ai_extracted=False,
            ))

    civil_dps = [
        ("Storm pond outflow",
         "Reviewed updated tributary area and outflow calc against AHJ template.",
         (("Action", "Verify pond outlet elevations against revised topo"),
          ("Concern", "Andrew flagged riprap quantity may be undersized"))),
        ("Erosion control",
         "SWPPP submittal package is 80% complete; tables pending Hossein's input.",
         ()),
    ]
    elec_dps = [
        ("Recloser settings",
         "Utility confirmed 138 kV settings are still under review — expected by Friday.",
         (("Risk", "Settings finalization may slip and push energization"),)),
        ("Ampacity study",
         "Aluminum wire selection assumes 90 C engineered soil values. Awaiting Dylan's report.",
         ()),
        ("Auxiliary loads / SCADA enclosure",
         "Confirmed 5 kVA transformer adequacy will be revisited after Dylan's calc.",
         ()),
    ]
    struct_dps = [
        ("Module rack tilt change",
         "Tilt change from 25 to 30 reviewed against load case — no impact on pile depth.",
         ()),
        ("Inverter pad rebar",
         "Vendor confirmed rebar schedule matches our typical detail.",
         ()),
    ]

    order = 0
    for label, content, subs in civil_dps:
        _add_dp(None, order, label, content, "Civil", subs)
        order += 1
    for label, content, subs in elec_dps:
        _add_dp(None, order, label, content, "Electrical", subs)
        order += 1
    for label, content, subs in struct_dps:
        _add_dp(None, order, label, content, "Structural", subs)
        order += 1

    actions = [
        ("Reach out to utility to confirm 138 kV recloser settings by Friday.",
         "Roashaael Mary John", date.today() + timedelta(days=4),  "open"),
        ("Finalize ampacity study with engineered soil values and circulate.",
         "Dylan Wraga, Arun Ramadass", date.today() + timedelta(days=7), "open"),
        ("Verify storm pond outlet elevations against revised topo.",
         "Andrew Proctor", date.today() + timedelta(days=3), "pending"),
        ("Submit SWPPP package once Hossein returns the tables.",
         "Hossein Karami, Jalen Wheeler", date.today() + timedelta(days=10), "open"),
        ("Confirm rebar schedule matches typical detail with vendor (closed).",
         "Cheyne Matheny", date.today() - timedelta(days=2), "completed"),
        ("Reissue civil drawings with revised module-rack tilt.",
         "Cheyne Matheny, Arun Ramadass", date.today() + timedelta(days=14), "open"),
        ("Coordinate with HDR IE on review-comment closeout.",
         "Roashaael Mary John", date.today() + timedelta(days=5), "pending"),
    ]
    for text, owner, due, status in actions:
        session.add(ActionItem(
            project_id=project.id,
            originating_meeting_id=meeting.id,
            text=text, owner=owner, due_date=due, status=status,
        ))

    deliverables = [
        ("Civil — 60% Design",     "30% drainage package",         "In Progress",
         date.today() + timedelta(days=14)),
        ("Electrical — One-line",  "Updated to reflect Aux loads", "In Progress",
         date.today() + timedelta(days=10)),
        ("Electrical — Ampacity",  "Final ampacity study + report","In Progress",
         date.today() + timedelta(days=18)),
        ("Structural — Calc set",  "Tilt-change load case rerun",  "In Progress",
         date.today() + timedelta(days=21)),
    ]
    for idx, (seg, task, status, delivery) in enumerate(deliverables):
        d = Deliverable(
            project_id=project.id,
            project_segment=seg, task=task,
            start_status=status, delivery_date=delivery,
            source="manual", schedule_version_added="V3",
        )
        session.add(d)
        session.flush()
        session.add(MeetingDeliverable(
            meeting_id=meeting.id, deliverable_id=d.id,
            order_index=idx, carried_from_prior=False,
        ))

    session.flush()
    return client, project, meeting


def _build_full_agenda_payload(meeting: Meeting) -> dict:
    """Build a fully-populated agenda payload — every section has content."""
    upcoming = date.today() + timedelta(days=7)

    disciplines = ["Civil", "Electrical", "Structural", "Permitting"]

    dp_by_d = {
        "Civil": [
            P(label="Drainage", content="Walk pond outflow with AHJ comment letter",
              discipline="Civil",
              sub_points=[
                  P(label="Decision",
                    content="Confirm pond outlet elevations vs. revised topo",
                    discipline="Civil"),
                  P(label="Risk",
                    content="Riprap quantity flagged as low; rework if confirmed",
                    discipline="Civil"),
              ]),
            P(label="SWPPP", content="Submittal package; Hossein's tables outstanding",
              discipline="Civil"),
        ],
        "Electrical": [
            P(label="Recloser settings",
              content="Friday utility deadline; escalate if no response",
              discipline="Electrical"),
            P(label="Ampacity study",
              content="Dylan's report due; align with engineered soil values",
              discipline="Electrical",
              sub_points=[
                  P(label="Follow-up",
                    content="Confirm 5 kVA transformer adequacy after report lands",
                    discipline="Electrical"),
              ]),
        ],
        "Structural": [
            P(label="Tilt-change load case",
              content="Confirm pile depth unaffected; sign off rerun",
              discipline="Structural"),
        ],
        "Permitting": [
            P(label="AHJ cycle",
              content="Pre-app meeting target this week; planning dept response next",
              discipline="Permitting"),
            P(label="Building dept",
              content="Items 4 and 7 still open in comment log",
              discipline="Permitting"),
        ],
    }

    recap_by_d: dict[str, list] = {d: [] for d in disciplines}
    for dp in sorted(meeting.discussion_points,
                     key=lambda d: d.order_index):
        if dp.parent_id is not None:
            continue
        disc = (dp.discipline or "General").capitalize()
        target = disc if disc in recap_by_d else "Civil"
        recap_by_d[target].append(P(
            label=dp.label or "", content=dp.content or "", discipline=target,
        ))

    risks = [
        {"description": "Utility recloser-settings delay",
         "impact":      "Pushes energization by 4-6 weeks",
         "likelihood":  "High",
         "mitigation":  "Weekly utility call; sponsor escalation if no Friday response",
         "owner":       "Roashaael Mary John"},
        {"description": "Geotech soil values variance",
         "impact":      "May force ampacity rework + cable resize",
         "likelihood":  "Medium",
         "mitigation":  "Preliminary borings before 60% submittal",
         "owner":       "Cheyne Matheny, Dylan Wraga"},
        {"description": "Transformer lead time",
         "impact":      "Cannot energize without it",
         "likelihood":  "Medium",
         "mitigation":  "Place vendor order at 60% to lock 18-week window",
         "owner":       "Rick Castillo"},
        {"description": "AHJ permitting cycle",
         "impact":      "Schedule risk on plan-set approval",
         "likelihood":  "Low",
         "mitigation":  "Pre-app meeting with planning department this week",
         "owner":       "Arun Ramadass"},
    ]

    decisions = [
        {"decision":       "Inverter brand selection",
         "description":    "SunPower vs. Sungrow vs. CPS",
         "impact_if_not":  "Vendor lock affects spare parts strategy",
         "required_by":    upcoming + timedelta(days=7),
         "owner":          "Rick Castillo"},
        {"decision":       "Module orientation",
         "description":    "East-West vs. South tilt for south parcel",
         "impact_if_not":  "Civil layout cannot lock until selected",
         "required_by":    upcoming + timedelta(days=14),
         "owner":          "Cheyne Matheny, Arun Ramadass"},
        {"decision":       "Recloser scheme",
         "description":    "Utility-spec vs. owner-supplied",
         "impact_if_not":  "Drawings cannot finalize until utility confirms",
         "required_by":    upcoming + timedelta(days=10),
         "owner":          "Roashaael Mary John"},
    ]

    schedule_changes = [
        {"project":              "Civil",
         "task":                 "60% Design package",
         "previous_date":        (date.today() + timedelta(days=10)).strftime("%m/%d/%Y"),
         "updated_date":         (date.today() + timedelta(days=14)).strftime("%m/%d/%Y"),
         "change_description":   "Drainage rework absorbed schedule slack",
         "reason_for_change":    "Pond outflow + riprap revisions",
         "impact":               "Net +4 days; no critical path impact"},
        {"project":              "Electrical",
         "task":                 "Ampacity study",
         "previous_date":        (date.today() + timedelta(days=14)).strftime("%m/%d/%Y"),
         "updated_date":         (date.today() + timedelta(days=18)).strftime("%m/%d/%Y"),
         "change_description":   "Awaiting engineered soil values from geotech",
         "reason_for_change":    "Geotech report delay",
         "impact":               "+4 days, critical path"},
        {"project":              "Structural",
         "task":                 "Calc rerun for tilt change",
         "previous_date":        (date.today() + timedelta(days=18)).strftime("%m/%d/%Y"),
         "updated_date":         (date.today() + timedelta(days=21)).strftime("%m/%d/%Y"),
         "change_description":   "Tilt change requires load-case rerun",
         "reason_for_change":    "Owner-directed module-tilt change",
         "impact":               "+3 days, slack absorbs"},
    ]

    return {
        "disciplines": disciplines,
        "dp_by_discipline": dp_by_d,
        "recap_by_discipline": recap_by_d,
        "risks": risks,
        "decisions": decisions,
        "schedule_changes": schedule_changes,
        "upcoming": upcoming,
    }


def main() -> None:
    init_db()
    session = get_session_factory()()
    try:
        _purge_prior_test_data(session)

        client, project, meeting = _build_test_meeting(session)
        session.commit()

        proj_slug = safe_filename_slug(project.name)

        print(f"Building meeting minutes for {meeting.title}...")
        mm_pdf = generate_meeting_minutes_pdf(meeting)
        mm_path = (
            OUTPUT_DIR
            / f"TEST_{proj_slug}_Meeting_Minutes_{meeting.meeting_date.isoformat()}.pdf"
        )
        mm_path.write_bytes(mm_pdf)
        print(f"  OK -> {mm_path}  ({len(mm_pdf):,} bytes)")

        print()
        print("Building pre-meeting agenda...")
        payload = _build_full_agenda_payload(meeting)
        upcoming = payload.pop("upcoming")

        # Modern API: build_draft_meeting_view (renamed from generate_next_agenda)
        draft = build_draft_meeting_view(
            session, project, upcoming,
            source_meeting_id=meeting.id,
        )

        carry_actions = list(open_actions(session, project.id))
        carry_deliv = list(deliverables_to_carry_forward(session, project.id))

        agenda_pdf = generate_premeeting_agenda_pdf(
            meeting=draft,
            prior_meeting=meeting,
            carry_actions=carry_actions,
            carry_deliverables=carry_deliv,
            schedule=session.query(Schedule)
                .filter_by(project_id=project.id).first(),
            **payload,
        )
        ag_path = (
            OUTPUT_DIR
            / f"TEST_{proj_slug}_Pre_Meeting_Agenda_{upcoming.isoformat()}.pdf"
        )
        ag_path.write_bytes(agenda_pdf)
        print(f"  OK -> {ag_path}  ({len(agenda_pdf):,} bytes)")

        print()
        print("Saving agenda to DB so it appears under History > Pre-Meeting Agendas...")

        dp_text_payload = {
            disc: _dps_to_text(tree)
            for disc, tree in payload["dp_by_discipline"].items()
        }
        for disc in payload["disciplines"]:
            dp_text_payload.setdefault(disc, "")
        recap_text_payload = {
            disc: _dps_to_text(tree)
            for disc, tree in payload["recap_by_discipline"].items()
        }
        for disc in payload["disciplines"]:
            recap_text_payload.setdefault(disc, "")

        attendees_payload = [
            {
                "full_name": a.full_name,
                "initials":  a.initials,
                "organization": a.organization,
            }
            for a in meeting.attendees
        ]
        open_actions_payload = [
            {
                "text":     a.text,
                "owner":    a.owner or "",
                "due_date": a.due_date.isoformat() if a.due_date else None,
                "status":   (a.status or "open").capitalize(),
            }
            for a in carry_actions
        ]
        decisions_payload = []
        for d in payload["decisions"]:
            d2 = dict(d)
            rb = d2.get("required_by")
            if rb and not isinstance(rb, str):
                d2["required_by"] = rb.isoformat()
            decisions_payload.append(d2)

        saved = save_agenda(
            session=session,
            project_id=project.id,
            upcoming_date=upcoming,
            source_meeting_id=meeting.id,
            title="Full coverage sample agenda",
            disciplines=payload["disciplines"],
            dp_text=dp_text_payload,
            recap_text=recap_text_payload,
            attendees=attendees_payload,
            open_actions=open_actions_payload,
            risks=payload["risks"],
            decisions=decisions_payload,
            schedule_changes=payload["schedule_changes"],
            meeting_duration_minutes=60,
        )
        session.commit()
        print(f"  OK -> Saved Agenda id={saved.id} on project {project.name!r}")
        print(
            "        Open the app -> History -> Pre-Meeting Agendas to "
            "see it; click Open to load into Next Agenda for testing."
        )

        print()
        print("Coverage summary:")
        print(f"  Meeting attendees ............ {len(meeting.attendees)}")
        print(f"  Meeting agenda items ......... {len(meeting.agenda_items)}")
        print(f"  Discussion points + sub ...... "
              f"{sum(1 + len(dp.sub_points) for dp in meeting.discussion_points if dp.parent_id is None)}")
        print(f"  Action items raised .......... {len(meeting.raised_actions)}")
        print(f"  Deliverables on meeting ...... {len(meeting.meeting_deliverables)}")
        print()
        print(f"  Agenda disciplines ........... {len(payload['disciplines'])}")
        print(f"  Agenda DP points ............. "
              f"{sum(len(v) for v in payload['dp_by_discipline'].values())}")
        print(f"  Agenda recap items ........... "
              f"{sum(len(v) for v in payload['recap_by_discipline'].values())}")
        print(f"  Agenda risks ................. {len(payload['risks'])}")
        print(f"  Agenda decisions ............. {len(payload['decisions'])}")
        print(f"  Agenda schedule changes ...... {len(payload['schedule_changes'])}")
        print(f"  Carry-forward actions ........ {len(carry_actions)}")
        print(f"  Carry-forward deliverables ... {len(carry_deliv)}")
        print()
        print("Done. Open the two PDFs above to review.")
    finally:
        session.close()


if __name__ == "__main__":
    main()
