"""add User model + attribution + attendee email

Revision ID: 512729ab4732
Revises: 336cc442b85e
Create Date: 2026-05-26 10:41:40.813600

Introduces the `users` table (Castillo PMs auto-upserted from their Entra
oid on first sign-in) plus `created_by_id` / `updated_by_id` FKs on the
write-heavy domain models (Meeting, Agenda, ActionItem, Note). Also adds
an `email` column on `meeting_attendees` so the Send page has direct
access to recipient addresses without a second roster lookup.

SQLite quirk: batch ALTER requires named constraints (it has to recreate
the whole table behind the scenes). The autogenerated migration left
`name=None` on the create_foreign_key calls, which alembic rejects with
"Constraint must have a name". Every FK below has an explicit name now.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '512729ab4732'
down_revision: Union[str, Sequence[str], None] = '336cc442b85e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('oid', sa.String(length=64), nullable=False),
        sa.Column('email', sa.String(length=200), nullable=True),
        sa.Column('name', sa.String(length=200), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('last_seen_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('oid'),
    )

    with op.batch_alter_table('action_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_action_items_created_by', 'users', ['created_by_id'], ['id']
        )
        batch_op.create_foreign_key(
            'fk_action_items_updated_by', 'users', ['updated_by_id'], ['id']
        )

    with op.batch_alter_table('agendas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_agendas_created_by', 'users', ['created_by_id'], ['id']
        )
        batch_op.create_foreign_key(
            'fk_agendas_updated_by', 'users', ['updated_by_id'], ['id']
        )

    with op.batch_alter_table('meeting_attendees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=200), nullable=True))

    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_meetings_created_by', 'users', ['created_by_id'], ['id']
        )
        batch_op.create_foreign_key(
            'fk_meetings_updated_by', 'users', ['updated_by_id'], ['id']
        )

    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_notes_created_by', 'users', ['created_by_id'], ['id']
        )
        batch_op.create_foreign_key(
            'fk_notes_updated_by', 'users', ['updated_by_id'], ['id']
        )


def downgrade() -> None:
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_notes_updated_by', type_='foreignkey')
        batch_op.drop_constraint('fk_notes_created_by', type_='foreignkey')
        batch_op.drop_column('updated_by_id')
        batch_op.drop_column('created_by_id')

    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_meetings_updated_by', type_='foreignkey')
        batch_op.drop_constraint('fk_meetings_created_by', type_='foreignkey')
        batch_op.drop_column('updated_by_id')
        batch_op.drop_column('created_by_id')

    with op.batch_alter_table('meeting_attendees', schema=None) as batch_op:
        batch_op.drop_column('email')

    with op.batch_alter_table('agendas', schema=None) as batch_op:
        batch_op.drop_constraint('fk_agendas_updated_by', type_='foreignkey')
        batch_op.drop_constraint('fk_agendas_created_by', type_='foreignkey')
        batch_op.drop_column('updated_by_id')
        batch_op.drop_column('created_by_id')

    with op.batch_alter_table('action_items', schema=None) as batch_op:
        batch_op.drop_constraint('fk_action_items_updated_by', type_='foreignkey')
        batch_op.drop_constraint('fk_action_items_created_by', type_='foreignkey')
        batch_op.drop_column('updated_by_id')
        batch_op.drop_column('created_by_id')

    op.drop_table('users')
