"""add User.preferences JSON column

Revision ID: a91e2c4f6b0d
Revises: 3343b67d1faa
Create Date: 2026-05-26 14:30:00.000000

Adds a JSON `preferences` column to `users` for per-user settings:
default portfolio, default meeting duration, default action due-date
offset (days), and an optional email signature appended to Graph emails.

SQLite quirk: batch ALTER on `users` requires explicit naming for the
unique constraint on `oid` (see the prior migration's note on named
constraints). The autogenerated migration would fail without it.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "a91e2c4f6b0d"
down_revision: Union[str, Sequence[str], None] = "3343b67d1faa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("preferences", sa.JSON(), nullable=True))


def downgrade() -> None:
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("preferences")
